//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyAlert.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CurrencyAlert.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Notifications.
        /// </summary>
        internal static string ChatNotifications {
            get {
                return ResourceManager.GetString("ChatNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above threshold.
        /// </summary>
        internal static string ChatWarningText {
            get {
                return ResourceManager.GetString("ChatWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Currency Alert Overlay.
        /// </summary>
        internal static string Commands_HideOverlayHelp {
            get {
                return ResourceManager.GetString("Commands_HideOverlayHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Currency Alert Overlay.
        /// </summary>
        internal static string Commands_ShowOverlayHelp {
            get {
                return ResourceManager.GetString("Commands_ShowOverlayHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Currency Alert Overlay.
        /// </summary>
        internal static string Commands_ToggleOverlayHelp {
            get {
                return ResourceManager.GetString("Commands_ToggleOverlayHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Configuration.
        /// </summary>
        internal static string CurrencyConfiguration {
            get {
                return ResourceManager.GetString("CurrencyConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently Selected.
        /// </summary>
        internal static string CurrentlySelected {
            get {
                return ResourceManager.GetString("CurrentlySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Ascending.
        /// </summary>
        internal static string DisplayAscending {
            get {
                return ResourceManager.GetString("DisplayAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Settings.
        /// </summary>
        internal static string DisplaySettings {
            get {
                return ResourceManager.GetString("DisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        internal static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Position.
        /// </summary>
        internal static string LockOverlay {
            get {
                return ResourceManager.GetString("LockOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal Display.
        /// </summary>
        internal static string MinimalOverlay {
            get {
                return ResourceManager.GetString("MinimalOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        internal static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay Settings.
        /// </summary>
        internal static string OverlaySettings {
            get {
                return ResourceManager.GetString("OverlaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to spend your.
        /// </summary>
        internal static string OverlayWarningText {
            get {
                return ResourceManager.GetString("OverlayWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Currency Icon.
        /// </summary>
        internal static string ShowCurrencyIcon {
            get {
                return ResourceManager.GetString("ShowCurrencyIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Currency Name.
        /// </summary>
        internal static string ShowCurrencyName {
            get {
                return ResourceManager.GetString("ShowCurrencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Overlay.
        /// </summary>
        internal static string ShowOverlay {
            get {
                return ResourceManager.GetString("ShowOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Warning Text.
        /// </summary>
        internal static string ShowWarningText {
            get {
                return ResourceManager.GetString("ShowWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Color.
        /// </summary>
        internal static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold.
        /// </summary>
        internal static string Threshold {
            get {
                return ResourceManager.GetString("Threshold", resourceCulture);
            }
        }
    }
}
